require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/vendor_sweets", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # VendorSweet. As you add validations to VendorSweet, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the headers
  # in order to pass any filters (e.g. authentication) defined in
  # VendorSweetsController, or in your router and rack
  # middleware. Be sure to keep this updated too.
  let(:valid_headers) {
    {}
  }

  describe "GET /index" do
    it "renders a successful response" do
      VendorSweet.create! valid_attributes
      get vendor_sweets_url, headers: valid_headers, as: :json
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      vendor_sweet = VendorSweet.create! valid_attributes
      get vendor_sweet_url(vendor_sweet), as: :json
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new VendorSweet" do
        expect {
          post vendor_sweets_url,
               params: { vendor_sweet: valid_attributes }, headers: valid_headers, as: :json
        }.to change(VendorSweet, :count).by(1)
      end

      it "renders a JSON response with the new vendor_sweet" do
        post vendor_sweets_url,
             params: { vendor_sweet: valid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:created)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "does not create a new VendorSweet" do
        expect {
          post vendor_sweets_url,
               params: { vendor_sweet: invalid_attributes }, as: :json
        }.to change(VendorSweet, :count).by(0)
      end

      it "renders a JSON response with errors for the new vendor_sweet" do
        post vendor_sweets_url,
             params: { vendor_sweet: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested vendor_sweet" do
        vendor_sweet = VendorSweet.create! valid_attributes
        patch vendor_sweet_url(vendor_sweet),
              params: { vendor_sweet: new_attributes }, headers: valid_headers, as: :json
        vendor_sweet.reload
        skip("Add assertions for updated state")
      end

      it "renders a JSON response with the vendor_sweet" do
        vendor_sweet = VendorSweet.create! valid_attributes
        patch vendor_sweet_url(vendor_sweet),
              params: { vendor_sweet: new_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:ok)
        expect(response.content_type).to match(a_string_including("application/json"))
      end
    end

    context "with invalid parameters" do
      it "renders a JSON response with errors for the vendor_sweet" do
        vendor_sweet = VendorSweet.create! valid_attributes
        patch vendor_sweet_url(vendor_sweet),
              params: { vendor_sweet: invalid_attributes }, headers: valid_headers, as: :json
        expect(response).to have_http_status(:unprocessable_entity)
        expect(response.content_type).to eq("application/json")
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested vendor_sweet" do
      vendor_sweet = VendorSweet.create! valid_attributes
      expect {
        delete vendor_sweet_url(vendor_sweet), headers: valid_headers, as: :json
      }.to change(VendorSweet, :count).by(-1)
    end
  end
end
